# By Marden's theorem:
# If the triangle vertices (z1, z2, z3) are the zeroes of p(z)
# Then, zeroes of p'(z) = 0 has to be +/- 13
# So we have p(z) = z^3 - 39z + C, where C is any constant

# By Vieta's formula:
# z1 + z2 + z3 = 0
# 
# z1z2 + z1z3 + z2z3 = -39
# ==> z1z2 + z3(z1 + z2) = -39
# ==> z1z2 - (z1 + z2)^2 = -39
# ==> z1^2 + z1z2 + z2^2 = 39

# So all our solutions can be generated by finding the Gaussian integers solutions for
# z1^2 + z1z2 + z2^2 = 39

# If we let X = 2z1 + z2 and Y = z2, then we have the Pell-like equation X^2 + 3Y^2 = 156.
# Let X = x1 + ix2, Y = y1 + iy2
# Real: x1^2 - x2^2 + 3y1^2 - 3y2^2 = 156
# Imag: x1x2 + 3y1y2 = 0

# From the imag:
# Let x1/y1 = gu / gv
# Then x2/y2 = 3hv / -hu
# Substitute to real: (g^2 - 3h^2)(u^2 + 3v^2) = 156

# Another family of solution:
# Let x1/y1 = 3gv / 3gu
# Then x2/y2 = ku / -kv
# Substitute to real: (3g^2 - k^2)(u^2 + 3v^2) = 156

# So we factorise 156 = A*B
# - u^2 + 3v^2 = B can be done by bruteforce
# - g^2 - 3h^2 = A is a Pell equation
#   - Find "base" solutions, then iteratively g, h = 2g + 3h, h + 2h
    # (By Brahmagupta identity, multiply by (2 + sqrt(3)), because 2^2 - 3*1 = 1)
# - 3g^2 - k^2 = A ==> k^2 - 3g^2 = -A, same Pell equation

import math


def get_factor_pairs(n):
    return [(n // i, i) for i in range(1, n + 1) if n % i == 0]


# Find all u^2 + 3v^2 = B
def get_uv(B):
    ret = []
    for u in range(math.isqrt(B)+1):
        v = math.isqrt((B - u*u) // 3)
        if u*u + 3*v*v == B:
            ret.extend(list(set([(u, v), (-u, v), (u, -v), (-u, -v)])))
    return ret


# Find "base" solution for g^2 - 3h^2 = A
def get_gh(A):
    ret = []
    for g in range(51):
        if g*g < A:
            continue
        h = math.isqrt((g*g - A) // 3)
        if g*g - 3*h*h == A:
            ret.extend(list(set([(g, h), (-g, h), (g, -h), (-g, -h)])))
    return ret


def A(N):
    ret = []

    def area(z1, z2, z3):
        A = z1[0]*z2[1] + z2[0]*z3[1] + z3[0]*z1[1]
        A -= z1[1]*z2[0] + z2[1]*z3[0] + z3[1]*z1[0]
        return abs(A)

    def check(x1, x2, y1, y2):
        if x1 % 2 != y1 % 2 or x2 % 2 != y2 % 2:
            return True
        z1 = ((x1 - y1) // 2, (x2 - y2) // 2)
        z2 = (y1, y2)
        z3 = (-z1[0] - z2[0], -z1[1] - z2[1])

        if max(abs(z1[0]), abs(z1[1]), abs(z2[0]), abs(z2[1]), abs(z3[0]), abs(z3[1])) <= N:
            ret.append(tuple(sorted([z1, z2, z3])))
            return True

        return False


    for A, B in get_factor_pairs(156):
        for u, v in get_uv(B):
            # A = g^2 - 3h^2
            for g, h in get_gh(A):
                while True:
                    x1, y1 = g*u, g*v
                    x2, y2 = 3*h*v, -h*u
                    if not check(x1, x2, y1, y2):
                        break
                    g, h = (2*g + 3*h, g + 2*h)

            for g, h in get_gh(-A):
                while True:
                    x1, y1 = 3*h*v, h*u
                    x2, y2 = g*u, -g*v

                    if not check(x1, x2, y1, y2):
                        break

                    g, h = (2*g + 3*h, g + 2*h)

    ret = list(set(ret))

    A = sum(area(z1, z2, z3) for z1, z2, z3 in ret)
    if A % 2 == 1:
        return str(A // 2) + '.5'
    return str(A // 2)


if __name__ == "__main__":
    print(A(8))
    print(A(10))
    print(A(100))
    print(A(1000))
    print(A(10**9))
